'use strict';

/**
 * AWS Lambda: notifications for red-flagged students. Run on a schedule.
 *
 * For each red row in RISK_SCORES_TABLE not yet notified (NOTIFY_RESEND=true
 * re-sends), SMS the parent via Africa's Talking and email the teacher via SES,
 * then stamp notifiedAt if every attempted channel succeeded.
 *
 * RISK_SCORES_TABLE item shape:
 *   {
 *     studentId, studentName, attendanceRate (0..1), totalScore (number),
 *     flagLevel: 'green' | 'amber' | 'red',
 *     topFeatures: [{ feature, contribution }, ...],
 *     parentPhone: '+2547...', teacherEmail: 'teacher@school.ke',
 *     notifiedAt?: ISO string
 *   }
 *   Partition key: studentId (S)
 *
 *
 * Local mode (AWS_ACCESS_KEY_ID unset or "placeholder", or NOTIFY_DRY_RUN=true)
 * logs the SMS and email instead of sending them. SES is not available in
 * af-south-1, so set SES_REGION to a supported region such as eu-west-1.
 */

const { ScanCommand, UpdateCommand } = require('@aws-sdk/lib-dynamodb');
const { SESClient, SendEmailCommand } = require('@aws-sdk/client-ses');

const { createDocClient, usingPlaceholderCredentials } = require('./lib/dynamo');

const RISK_TABLE = process.env.RISK_SCORES_TABLE || 'risk-scores';
const DRY_RUN = usingPlaceholderCredentials() || process.env.NOTIFY_DRY_RUN === 'true';
const RESEND = process.env.NOTIFY_RESEND === 'true';

const ddb = createDocClient();
const ses = new SESClient({ region: process.env.SES_REGION || process.env.AWS_REGION || 'eu-west-1' });

// formatting
const FEATURE_LABELS = {
  attendance_rate_w1: 'attendance, last 2 weeks',
  attendance_rate_w2: 'attendance, weeks 3-4 back',
  attendance_rate_w3: 'attendance, weeks 5-6 back',
  longest_absence_streak: 'longest unbroken absence',
  absence_episode_count: 'number of absence spells',
  dow_concentration: 'absences clustered on one weekday',
  attendance_trend: 'recent attendance trend'
};

function pct(rate) {
  return rate == null || Number.isNaN(rate) ? 'n/a' : `${Math.round(rate * 100)}%`;
}

function topThreeFeatures(topFeatures) {
  let list = topFeatures;
  if (typeof list === 'string') {
    try {
      list = JSON.parse(list);
    } catch {
      list = [];
    }
  }
  return (list || [])
    .slice()
    .sort((a, b) => Math.abs(b.contribution ?? 0) - Math.abs(a.contribution ?? 0))
    .slice(0, 3)
    .map((f) => ({
      label: FEATURE_LABELS[f.feature] || f.feature,
      contribution: Number(f.contribution ?? 0)
    }));
}

function smsBody(student) {
  return (
    `SmartAttend alert: ${student.studentName} has been flagged for high absenteeism ` +
    `risk (attendance ${pct(student.attendanceRate)}). Please contact the school. ` +
    `Reply STOP to opt out.`
  );
}

function emailBodies(student, features) {
  const featureLines = features
    .map((f, i) => `  ${i + 1}. ${f.label} (weight ${f.contribution.toFixed(2)})`)
    .join('\n');

  const text =
    `Student: ${student.studentName} (${student.studentId})\n` +
    `Risk flag: RED\n` +
    `Attendance rate: ${pct(student.attendanceRate)}\n` +
    `Risk score: ${Number(student.totalScore).toFixed(2)}\n\n` +
    `Top contributing factors:\n${featureLines}\n\n` +
    `Generated by SmartAttend AI at ${new Date().toISOString()}.`;

  const rows = features
    .map(
      (f, i) =>
        `<tr><td>${i + 1}</td><td>${f.label}</td><td style="text-align:right">${f.contribution.toFixed(
          2
        )}</td></tr>`
    )
    .join('');

  const html =
    `<h2>Absenteeism risk alert - RED</h2>` +
    `<p><strong>${student.studentName}</strong> (${student.studentId})</p>` +
    `<ul>` +
    `<li>Attendance rate: <strong>${pct(student.attendanceRate)}</strong></li>` +
    `<li>Risk score: <strong>${Number(student.totalScore).toFixed(2)}</strong></li>` +
    `</ul>` +
    `<h3>Top contributing factors</h3>` +
    `<table border="1" cellpadding="6" cellspacing="0">` +
    `<thead><tr><th>#</th><th>Factor</th><th>Weight</th></tr></thead><tbody>${rows}</tbody></table>` +
    `<p style="color:#666;font-size:12px">Generated by SmartAttend AI at ${new Date().toISOString()}.</p>`;

  return { text, html };
}

// channels
async function sendSms(to, message) {
  if (DRY_RUN) {
    console.log('[notify][dry-run] SMS', { to, message });
    return { ok: true, dryRun: true };
  }
  const url = process.env.AT_API_URL || 'https://api.africastalking.com/version1/messaging';
  const form = new URLSearchParams({
    username: process.env.AT_USERNAME || 'sandbox',
    to,
    message
  });
  if (process.env.AT_SENDER_ID) form.set('from', process.env.AT_SENDER_ID);

  const res = await fetch(url, {
    method: 'POST',
    headers: {
      apiKey: process.env.AT_API_KEY || '',
      'Content-Type': 'application/x-www-form-urlencoded',
      Accept: 'application/json'
    },
    body: form
  });
  const data = await res.json().catch(() => ({}));
  const recipient = data?.SMSMessageData?.Recipients?.[0];
  const ok = res.ok && recipient && /Success|Sent|Queued/i.test(recipient.status || '');
  return { ok, status: recipient?.status, raw: data };
}

async function sendEmail(to, student, features) {
  const { text, html } = emailBodies(student, features);
  const subject = `[SmartAttend] RED absenteeism risk: ${student.studentName}`;

  if (DRY_RUN) {
    console.log('[notify][dry-run] EMAIL', { to, subject, text });
    return { ok: true, dryRun: true };
  }
  await ses.send(
    new SendEmailCommand({
      Source: process.env.SES_FROM_ADDRESS,
      Destination: { ToAddresses: [to] },
      Message: {
        Subject: { Data: subject, Charset: 'UTF-8' },
        Body: {
          Text: { Data: text, Charset: 'UTF-8' },
          Html: { Data: html, Charset: 'UTF-8' }
        }
      }
    })
  );
  return { ok: true };
}

// data
async function fetchRedFlags() {
  const items = [];
  let ExclusiveStartKey;
  do {
    const res = await ddb.send(
      new ScanCommand({
        TableName: RISK_TABLE,
        FilterExpression: RESEND
          ? '#f = :red'
          : '#f = :red AND attribute_not_exists(notifiedAt)',
        ExpressionAttributeNames: { '#f': 'flagLevel' },
        ExpressionAttributeValues: { ':red': 'red' },
        ExclusiveStartKey
      })
    );
    items.push(...(res.Items ?? []));
    ExclusiveStartKey = res.LastEvaluatedKey;
  } while (ExclusiveStartKey);
  return items;
}

async function markNotified(studentId, channels) {
  if (DRY_RUN) return;
  await ddb.send(
    new UpdateCommand({
      TableName: RISK_TABLE,
      Key: { studentId },
      UpdateExpression: 'SET notifiedAt = :ts, notifiedChannels = :ch',
      ExpressionAttributeValues: { ':ts': new Date().toISOString(), ':ch': channels }
    })
  );
}

// handler
exports.handler = async () => {
  const students = await fetchRedFlags();
  console.log(`[notify] ${students.length} red-flag student(s)${DRY_RUN ? ' (dry run)' : ''}`);

  const summary = { processed: 0, smsSent: 0, emailsSent: 0, skipped: [], errors: [] };

  for (const student of students) {
    summary.processed += 1;
    const features = topThreeFeatures(student.topFeatures);
    const attempted = [];
    const succeeded = [];

    if (student.parentPhone) {
      attempted.push('sms');
      try {
        const r = await sendSms(student.parentPhone, smsBody(student));
        if (r.ok) {
          summary.smsSent += 1;
          succeeded.push('sms');
        } else {
          summary.errors.push({ studentId: student.studentId, channel: 'sms', detail: r.status || r.raw });
        }
      } catch (err) {
        summary.errors.push({ studentId: student.studentId, channel: 'sms', detail: err.message });
      }
    } else {
      summary.skipped.push({ studentId: student.studentId, reason: 'no parentPhone' });
    }

    if (student.teacherEmail) {
      attempted.push('email');
      try {
        await sendEmail(student.teacherEmail, student, features);
        summary.emailsSent += 1;
        succeeded.push('email');
      } catch (err) {
        summary.errors.push({ studentId: student.studentId, channel: 'email', detail: err.message });
      }
    } else {
      summary.skipped.push({ studentId: student.studentId, reason: 'no teacherEmail' });
    }

    if (attempted.length > 0 && attempted.length === succeeded.length) {
      try {
        await markNotified(student.studentId, succeeded);
      } catch (err) {
        summary.errors.push({ studentId: student.studentId, channel: 'markNotified', detail: err.message });
      }
    }
  }

  console.log('[notify] done', summary);
  return summary;
};

exports._internals = { topThreeFeatures, smsBody, emailBodies, pct };
